In [63]:
import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo

Згенеруємо дані

In [64]:
# fetch dataset Перший набір
wine = fetch_ucirepo(id=109) 
  
# data (as pandas dataframes) 
X = wine.data.features 
y = wine.data.targets 

In [65]:
from sklearn.datasets import make_classification

In [66]:
x_g, y_g = make_classification(n_samples=181, n_features=16, n_informative=3, n_redundant=4)
x_g

array([[-0.76140922,  0.11431366,  0.33376965, ...,  1.13047408,
         0.57047797,  0.22553018],
       [ 2.1042099 ,  0.85005082, -0.74935695, ..., -0.4050164 ,
        -1.46956242,  1.13532303],
       [ 1.41463755, -0.39977483,  1.05157174, ...,  0.60679048,
        -1.77791874, -1.30066825],
       ...,
       [ 0.86071483,  0.54555554,  0.15041709, ...,  0.08984181,
        -0.82099997, -1.21116543],
       [-0.65516929,  1.54784747, -0.54755183, ...,  1.57662577,
        -0.61437948,  0.64050888],
       [ 0.00300501,  0.78134044, -0.92892264, ..., -0.44145915,
        -0.05976929, -1.05744972]])

3. Оцінити важливість ознак, використовуючи наступні алгоритми, реалізовані в scikit-learn python: 
- Univariate feature selection,

In [67]:
from sklearn.feature_selection import GenericUnivariateSelect

In [68]:
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

In [69]:
gUS = GenericUnivariateSelect()
x = gUS.fit_transform(x, yy.values.ravel())
#gUS.fit(x,yy)
#x = gUS.transform(x)

In [70]:
x.shape

(178, 1)

In [71]:
X_gen.shape

(181, 16)

In [72]:
gUS.get_support()

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False])

При застосуванні Generic Unvariate Select кількість характеристик скорочується до однієї, для такої речі як відрізняти вино за характиристиками виглядає дивно. Причому цей параметр - фламаноїди

In [73]:
gUS1 = GenericUnivariateSelect()
X_gen = gUS1.fit_transform(X_gen, Y_gen.ravel())

In [74]:
X_gen.shape

(181, 1)

In [75]:
X_gen

array([[-1.65851076],
       [ 0.2914561 ],
       [ 0.36796532],
       [-0.16664689],
       [-0.53606983],
       [ 2.86558342],
       [ 1.95351352],
       [ 1.74202447],
       [ 2.20509286],
       [ 0.74775288],
       [ 1.4592632 ],
       [ 0.16859317],
       [-0.94696562],
       [-1.72285598],
       [ 1.01743351],
       [ 1.83860246],
       [ 0.08605833],
       [-1.07723946],
       [-1.23876315],
       [ 0.03739207],
       [-0.69366746],
       [-2.76332207],
       [-5.24853981],
       [ 0.39972426],
       [-0.42025574],
       [-0.10743825],
       [ 1.60450618],
       [-1.60258779],
       [ 2.01304657],
       [ 0.03126843],
       [-0.95975669],
       [ 1.33728729],
       [-1.3345921 ],
       [ 2.259574  ],
       [ 1.88367483],
       [-2.22083814],
       [ 0.34482983],
       [-0.30240669],
       [ 0.81628672],
       [-2.89891415],
       [ 0.15673104],
       [ 3.47242242],
       [-2.15114363],
       [-4.94097534],
       [-3.69398346],
       [ 0

In [76]:
gUS1.scores_

array([1.38011386e-01, 8.30637723e-01, 3.14158821e-01, 3.54770824e+01,
       2.06216634e+01, 1.77946625e+01, 1.03579772e+00, 3.69469151e+01,
       6.55368853e-03, 3.24195875e-03, 1.86098745e+01, 5.25284191e+00,
       4.30266673e+01, 3.60447098e+00, 1.86482709e+01, 1.69130139e-01])

In [77]:
gUS1.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False])

З самостійно згенерованим датасетом так само обрано лише одну ознаку, хоча при генерації задавалося три важливі. Тому, на мою думку цей алгоритм не підійшов у обох датасетах

Recursive feature elimination

In [78]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [79]:
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

У клітинці вище - код з присвоєнням значень для дослідження. Я потім зрозумів що можна було зробити функцію, але не хотів переробляти роботу бо це не дуже релевантно

In [80]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, step=1)
selector = selector.fit(x, yy.values.ravel())
selector.support_

array([ True, False, False, False, False,  True,  True,  True, False,
       False,  True,  True, False])

In [81]:
sum(selector.support_)

6

При застосуванні recursive feature elimination було визначено 6 важливих ознак у датасету. Для естіматора тут використовується Support Vector Regression з лінійним ядром. Визначені параметри: Alcohol, Total phenols, Flavanoids, Nonflavanoid phenols, HueOD280/OD315 of diluted wines, Proline, 

In [82]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, step=1)
selector = selector.fit(X_gen, Y_gen)
selector.support_

array([False,  True,  True,  True,  True, False,  True, False, False,
       False, False,  True,  True,  True, False, False])

In [83]:
sum(selector.support_)

8

8 важливих ознак було визначено у згенерованому датасеті, на противагу до 3 згенерованих важливих. Це все ж краще за попередній метод, але не дуже.

Recursive feature elimination with cross-validation to select features.

In [84]:
from sklearn.feature_selection import RFECV

In [85]:
estimator = SVR(kernel="linear")
selector = RFECV(estimator, step=1, cv=5)
selector = selector.fit(x, yy.values.ravel())
selector.support_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [86]:
selector.ranking_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Оскільки цей алгоритм залишив всі стовпчики, то в певній мірі він може бути найточнішим, оскільки початковий датасет (якщо вірити його сторінці) вже був скорочений плюс, за логікою можна побачити, що всі характеристики все ж є потрібними

In [87]:
estimator = SVR(kernel="linear")
selector = RFECV(estimator, step=1, cv=5)
selector = selector.fit(X_gen, Y_gen)
selector.support_

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True])

In [88]:
selector.ranking_

array([1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1])

In [89]:
sum(selector.support_)

14

Для згенерованого датасету було обрано 14 ознак. Ця робота дещо перестворювалася, тому надам фактом, що для іншого згенерованого датасету цим алгоритмом було отримано 2 та 16 важливих при 3 заданих при генерації. Також я не рекомендую застосування у цьому варіанті алгоритму підтримуючих векторів через суттєво повільну роботу. В подальших алгоритмах я заміню на KNN

Sequential Feature Selection

In [90]:
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

In [91]:
from sklearn.feature_selection import SequentialFeatureSelector

In [92]:
from sklearn.neighbors import KNeighborsClassifier
estimator = KNeighborsClassifier(n_neighbors=3)

In [93]:
sfs = SequentialFeatureSelector(estimator, n_features_to_select='auto')
sfs.fit(x, yy.values.ravel())
sfs.get_support()

array([ True, False,  True, False, False,  True,  True, False,  True,
        True, False, False, False])

In [94]:
sfs.transform(X).shape

(178, 6)

Використовуючи KNN з трьома сусідами у якості оцінщика ми отримали результат з шістьмома характеристиками для нашого датасету з вином. Це  Alcohol, Ash, Total, phenols, Flavanoids, Proanthocyanins, Color, intensity 

In [95]:
sfs = SequentialFeatureSelector(estimator)
sfs.fit(X_gen, Y_gen)
sfs.get_support()

C:\Users\Borya\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_selection\_sequential.py:188: FutureWarning: Leaving `n_features_to_select` to None is deprecated in 1.0 and will become 'auto' in 1.3. To keep the same behaviour as with None (i.e. select half of the features) and avoid this warning, you should manually set `n_features_to_select='auto'` and set tol=None when creating an instance.
  warnings.warn(


array([False,  True, False, False,  True,  True, False,  True, False,
       False,  True,  True,  True, False, False,  True])

In [96]:
sfs.transform(X_gen).shape

(181, 8)

Для згенерованого датасету алгоритм виділив 8 параметрів

Sequential Feature Selection 'backward'

In [97]:
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

In [98]:
estimator = KNeighborsClassifier(n_neighbors=3)
sfs = SequentialFeatureSelector(estimator,direction='backward')
sfs.fit(x, yy.values.ravel())
sfs.get_support()

C:\Users\Borya\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_selection\_sequential.py:188: FutureWarning: Leaving `n_features_to_select` to None is deprecated in 1.0 and will become 'auto' in 1.3. To keep the same behaviour as with None (i.e. select half of the features) and avoid this warning, you should manually set `n_features_to_select='auto'` and set tol=None when creating an instance.
  warnings.warn(


array([ True, False, False,  True, False, False,  True, False,  True,
        True, False,  True, False])

In [99]:
sfs.transform(X).shape

(178, 6)

6 параметрів, не такі як у попередньому, а такі: Alcohol, Alcalinity of ash, Flavanoids, Proanthocyanins, Color intensity, Proline,

In [100]:
sfs = SequentialFeatureSelector(estimator)
sfs.fit(X_gen, Y_gen)
sfs.get_support()

C:\Users\Borya\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_selection\_sequential.py:188: FutureWarning: Leaving `n_features_to_select` to None is deprecated in 1.0 and will become 'auto' in 1.3. To keep the same behaviour as with None (i.e. select half of the features) and avoid this warning, you should manually set `n_features_to_select='auto'` and set tol=None when creating an instance.
  warnings.warn(


array([False,  True, False, False,  True,  True, False,  True, False,
       False,  True,  True,  True, False, False,  True])

In [101]:
sfs.transform(X_gen).shape

(181, 8)

Результат ідентичний відповіді з параметром forward

SelectFromModel with support of L1-regularisation

In [102]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

In [103]:
selector = SelectFromModel(estimator=LogisticRegression(max_iter=148800)).fit(x, yy.values.ravel())
selector.estimator_.coef_

array([[ 6.49944714e-01,  5.08016209e-01,  7.08591565e-01,
        -2.23728757e-01, -1.96616389e-02,  2.39876447e-01,
         8.26858387e-01,  9.41795564e-02,  8.70120312e-02,
         2.25974666e-01, -6.27955247e-03,  6.51419999e-01,
         9.37498658e-03],
       [-7.56853507e-01, -7.98605601e-01, -8.50009139e-01,
         1.18972978e-01, -1.55414404e-02,  1.75332174e-01,
         4.08024226e-01,  4.63440141e-02,  3.95937351e-01,
        -1.05773342e+00,  3.45193806e-01,  3.38040520e-02,
        -8.95596332e-03],
       [ 1.06908793e-01,  2.90589391e-01,  1.41417575e-01,
         1.04755779e-01,  3.52030793e-02, -4.15208621e-01,
        -1.23488261e+00, -1.40523570e-01, -4.82949382e-01,
         8.31758752e-01, -3.38914253e-01, -6.85224051e-01,
        -4.19023252e-04]])

In [104]:
selector.threshold_

1.0823831585413597

In [105]:
selector.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
        True, False,  True, False])

In [106]:
selector.transform(x)

array([[14.23,  1.71,  2.43,  3.06,  5.64,  3.92],
       [13.2 ,  1.78,  2.14,  2.76,  4.38,  3.4 ],
       [13.16,  2.36,  2.67,  3.24,  5.68,  3.17],
       ...,
       [13.27,  4.28,  2.26,  0.69, 10.2 ,  1.56],
       [13.17,  2.59,  2.37,  0.68,  9.3 ,  1.62],
       [14.13,  4.1 ,  2.74,  0.76,  9.2 ,  1.6 ]])

Знову 6 параметрів, але на цей раз це: Alcohol, Malic acid, Ash, Flavanoids, Color intensity, Proline,

In [107]:
selector = SelectFromModel(estimator=LogisticRegression()).fit(X_gen, Y_gen)
selector.estimator_.coef_

array([[-0.06796477,  0.26237879, -0.28845048,  0.22890985,  0.38536115,
        -0.00520903,  0.23610669, -0.14340407,  0.14040197,  0.14500928,
         0.09907993, -0.36642742, -0.23413734, -0.34677314, -0.14641197,
        -0.19038487]])

In [108]:
selector.threshold_

0.20540067201122586

In [109]:
selector.get_support()

array([False,  True,  True,  True,  True, False,  True, False, False,
       False, False,  True,  True,  True, False, False])

In [110]:
selector.transform(X_gen)

array([[ 0.11431366,  0.33376965, -0.15794801, ...,  0.09010132,
        -1.65851076,  1.13047408],
       [ 0.85005082, -0.74935695,  1.0235584 , ...,  2.25625091,
         0.2914561 , -0.4050164 ],
       [-0.39977483,  1.05157174,  1.10207732, ...,  0.36697572,
         0.36796532,  0.60679048],
       ...,
       [ 0.54555554,  0.15041709,  1.07437408, ..., -0.94577654,
        -1.10546913,  0.08984181],
       [ 1.54784747, -0.54755183,  0.20904906, ..., -0.94558892,
         0.12963228,  1.57662577],
       [ 0.78134044, -0.92892264,  0.41153135, ...,  1.2877948 ,
        -0.70109726, -0.44145915]])

Теж 8 параметрів, але відрізняється від попереднього 

SelectFromModel with random forest

In [111]:
from sklearn.ensemble import RandomForestClassifier
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()
estimator = RandomForestClassifier()

In [112]:
selector = SelectFromModel(estimator=estimator).fit(x, yy.values.ravel())
selector.threshold_

0.07692307692307693

In [113]:
selector.get_support()

array([ True, False, False, False, False, False,  True, False, False,
        True,  True,  True,  True])

In [114]:
selector.transform(x).shape

(178, 6)

6 характеристик: Alcohol, Flavanoids, Color intensity, HueOD280/OD315 of diluted wines, Proline

In [115]:
selector = SelectFromModel(estimator=estimator).fit(X_gen, Y_gen)
selector.threshold_

0.0625

In [116]:
selector.get_support()

array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True, False,  True, False,  True, False])

In [117]:
selector.transform(X_gen).shape

(181, 7)

ColumnSelector

In [118]:
from mlxtend.feature_selection import ColumnSelector
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

col_selector = ColumnSelector((0,7))
col_selector.transform(X_gen).shape

(181, 2)

In [119]:
col_selector = ColumnSelector((0,7))
col_selector.transform(x).shape

(178, 2)

Можливо я невірно зрозумів алгоритм чи матеріали, але за допомогою цього можна вибирати саме самому. Не бачу більше особливостей для опису

SequentialFeatureSelector

In [120]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
x = X.copy()
yy = y.copy()
X_gen = x_g.copy()
Y_gen = y_g.copy()

In [121]:
knn = KNeighborsClassifier(n_neighbors=4)
sfs1 = SFS(knn,k_features=(1,5))

sfs1 = sfs1.fit(x, yy.values.ravel())

In [122]:
sfs1.transform(x).shape

(178, 4)

У цьому випадку отримано 4 характеристики, що менше ніж зазвичай у решти.

In [123]:
knn = KNeighborsClassifier(n_neighbors=4)
sfs1 = SFS(knn,k_features=(1,5))

sfs1 = sfs1.fit(X_gen, Y_gen)
sfs1.transform(X_gen).shape

(181, 4)

Найближче до заданих параметрів при генерації, але в середньому менше ніж давали інші алгоритми для згенерованого датасета

Висновки

Виконавши роботу я розглянув алгоритми для зменшення кількості ознак у датасетів, а саме визначення найважливіших з них. Було використано методи Univariate feature selection, - Recursive feature elimination (RFE) та його модифікацію з крос-валідацією (RFECV), - Sequential Feature Selection, - SelectFromModel та ColumnSelector, які реалізовані у бібліотеках mlxtend та sklearn.
Більшість алгоритмів дали, що для взятого мною датасету про склад вина найважливішими є 6 чинників. І хоча точний список варіюється, частина його залишається для більшості алгоритмів однаковою: Alcohol, Flavanoids, Color intensity. Можна припустити що це най най важливіші ознаки.
Як щодо згенерованого датасету, то попри задані 3 важливі параметри жоден алгоритм саме стільки не визначив, а визначав зазвичай біля 8 характеристик для опису.

Якщо говорити про алгоритми, то ColumnSelector мені здався ручним інструментом, а найкращими за роботою стали Sequential Feature Selection, - SelectFromModel, десь так само точно працювали  Recursive feature elimination (RFE) та його модифікацію з крос-валідацією (RFECV). Univariate feature selection Вийшов найслабшим